### ISSUE TITLE
Use template repos

### ISSUE THREAD

**Issue by LudovicDeMatteis** [Simple-Robotics/aligator-cmake-example-project#1]
I believe it would be easier to make this project a public template project.

**Comment by ManifoldFR** [comment]
Excellent suggestion! I'll look into how these things work.

**Comment by ManifoldFR** [comment]
It ended up being just a [button in the repo settings](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository#about-template-repositories) somehow

Is that what you were thinking @LudovicDeMatteis ?

**Comment by LudovicDeMatteis** [comment]
Yes exactly, this way people can directly use this as a template for new github projects. 
Closing this remark
